services:

  postgres:

    image: postgres:16

    container_name: lm_postgres

    restart: always

    environment:

      POSTGRES_USER: lmgroup

      POSTGRES_PASSWORD: lmgroup123

      POSTGRES_DB: smartclinic

    ports:

      - "5432:5432"

    volumes:

      - postgres_data:/var/lib/postgresql/data

volumes:

  postgres_data: